version: "3"

services:
  app:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    # command: node dist/main
    ports:
      - 5000:5000
    depends_on:
      - postgres
    networks:
      - app-network
    restart: always
    environment:
      - DB_HOST=postgres
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: db
    ports:
      - 5432:5432
    volumes:
      - ./db/postgres/data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
